<?php
/**
 * Created by PhpStorm.
 * User: schr1ger
 * Date: 021 21.09.18
 * Time: 15:40
 */

namespace app\widgets;
use app\models\Rental;
use Yii;
use yii\base\Widget;
use app\helper\PseudoCrypt;
use app\models\RentalGarage;


class Bikesform extends Widget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $session = Yii::$app->session;
        $rentals = Rental::find()->asArray()->all();
        $u_coord = [-8.624073, 115.169085];
        $session->set('location_from_map', implode('|', $u_coord));
        $session->set('name_from_map', 'Kuta, Bali');

        foreach ($rentals as $rental) {
            /* @var $rental Rental */
            $r_radius = $rental['radius'];
            $r_coord = explode('|', $rental['coord']);
            $u_radius = PseudoCrypt::latlng2distance($u_coord[0], $u_coord[1], $r_coord[0], $r_coord[1]);
            if ($u_radius <= $r_radius) {
                $rent_idsp[] = $rental['id'];
            }
        }

        if (isset($rent_idsp) && is_array($rent_idsp)) {
            $model = RentalGarage::find()->with('condition', 'bike', 'bikeprice')->asArray()->where(['status' => 1, 'rental_id' => $rent_idsp])->all();
            $photos = [];
            if (!empty($model)) {
                $bikes = PseudoCrypt::getBikes($model);
                $session->set('bikes', $bikes);
                return $this->render('form-bike', [
                    'model' => $bikes,
                ]);

            }
        }

    }

}