<?php
/**
 * Created by PhpStorm.
 * User: schr1ger
 * Date: 005 05.10.18
 * Time: 17:58
 */

namespace app\widgets;


use app\models\Pages;
use yii\base\Widget;

class Hmenu extends Widget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $pages = Pages::find()->all();
        if($pages){
            $i = 0;
            $links = [];
            foreach ($pages as $page){
                /* @var $page \app\models\Pages */
                if($page->page_menu && $page->alias){
                    $links[$i]['alias'] = $page->alias;
                    $links[$i]['title'] = $page->page_menu;
                }
                $i++;
            }
            if(!empty($links)){
                return $this->render('header',['links' => $links]);
            }else{
                return false;
            }
        }
    }

}