<?php
/**
 * Created by PhpStorm.
 * User: trufanov
 * Date: 16.04.2018
 * Time: 16:44
 */
namespace app\modules\rental;
use yii\filters\AccessControl;
use app\models\Rental;
class Module extends \yii\base\Module
{

    /**
     * @inheritdoc
     */
    public $controllerNamespace = 'app\modules\rental\controllers';
    public $defaultRoute = 'rental';

    /**
     * @inheritdoc
     */

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    // разрешаем аутентифицированным пользователям
                    [
                        'actions' => ['index','add', 'edit','delete', 'account'],
                        'allow' => true,
                        //'roles' => ['@'],
                        'matchCallback' => function ($rule, $action){
                            $hash = \Yii::$app->request->get('hash');
                            if(!$hash){
                                if( \Yii::$app->session->has('hash')){
                                    $hash = \Yii::$app->session->get('hash');
                                }else{
                                    return false;
                                }
                            }else{
                                \Yii::$app->session->set('hash', $hash);
                            }
                            $rental = Rental::find()->where(['hash' => $hash])->one();
                            if($rental){
                                /* @var $rental \app\models\Rental */
                                \Yii::$app->session->set('auth', true);
                                \Yii::$app->session->set('region_id', $rental->region_id);
                                \Yii::$app->session->set('radius', $rental->radius);
                                \Yii::$app->session->set('rental_id', $rental->id);
                                \Yii::$app->session->set('name', $rental->name);
                                return true;
                            }else{
                                return false;
                            }
                        },
                    ],
                    [
                        'actions' => ['error', 'changestatus'],
                        'allow' => true,
                    ]
                ],
                'denyCallback' => function($rule, $action) {
                    return $action->controller->redirect('/rental/error');
                },
            ],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}