<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Big mileage' => '',
    'Book a bike in 2 minutes! Free delivery to hotel or your villa.' => '',
    'Booking' => '',
    'Choose bike' => '',
    'Confirm' => '',
    'Delivery the bike throughout the day.' => '',
    'E-mail' => '',
    'From' => '',
    'Helmets' => '',
    'If you have any question please' => '',
    'Low mileage' => '',
    'Name' => '',
    'New bike' => '',
    'Payment on delivery, we only accept cash.' => '',
    'Personal info' => '',
    'Phone Number' => '',
    'Pick and drop at' => '',
    'Pickup and drop at' => '',
    'Please choose date.' => '',
    'Please enter a email' => '',
    'Please enter a name' => '',
    'Please enter a phone' => '',
    'Rent a perfect bike in Bali' => '',
    'Rent bike for' => '',
    'Reservation Total' => '',
    'STEP {0} OF {1}' => '',
    'Service fee' => '',
    'Thank you' => '',
    'The date of return should be after the date of the lease.' => '',
    'To' => '',
    'Your order has been processed. We will contact you shortly!' => '',
    'Your scooter or motorbike will be delivered with' => '',
    'back' => '',
    'choose date' => '',
    'contact us' => '',
    'day' => '',
    'days' => '',
    'either 1 or 2 clean and sanitized helmets.' => '',
    'free' => '',
    'from' => '',
    'month' => '',
    'to' => '',
    'type your WhatsApp (with country code)' => '',
    'type your email' => '',
    'type your name' => '',
    '{0} helmet' => '',
];
