<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "operations".
 *
 * @property int $id
 * @property int $rental_id
 * @property int $order_id
 * @property int $sum
 * @property string $operations
 * @property string $date
 *
 * @property Zakaz $order
 * @property Rental $rental
 */
class Operations extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'operations';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['rental_id', 'order_id', 'sum'], 'integer'],
            [['date', 'operations'], 'safe'],
            [['order_id'], 'exist', 'skipOnError' => true, 'targetClass' => Zakaz::className(), 'targetAttribute' => ['order_id' => 'id']],
            [['rental_id'], 'exist', 'skipOnError' => true, 'targetClass' => Rental::className(), 'targetAttribute' => ['rental_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('admin/operations', 'ID'),
            'rental_id' => Yii::t('admin/operations', 'Rental ID'),
            'order_id' => Yii::t('admin/operations', 'Order ID'),
            'sum' => Yii::t('admin/operations', 'Sum'),
            'operations' => Yii::t('admin/operations', 'Operations'),
            'date' => Yii::t('admin/operations', 'Date'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrder()
    {
        return $this->hasOne(Zakaz::className(), ['id' => 'order_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRental()
    {
        return $this->hasOne(Rental::className(), ['id' => 'rental_id']);
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        if ($this->rental_id == null) {
            if(isset($changedAttributes['rental_id']))
                $rental_id = $changedAttributes['rental_id'];
        } else {
            $rental_id = $this->rental_id;
        }

        if(isset($rental_id))
            $rental = Rental::find()->where(['id' => $rental_id])->one();

        if (isset($rental)) {
            $sum = Operations::find()->where(['rental_id' => $rental_id])->sum('sum');
            $rental->balance = $sum;
            $rental->save();
        }
    }

    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
        $rental = Rental::find()->where(['id' => $this->rental_id])->one();
        if ($rental) {
            $sum = Operations::find()->where(['rental_id' => $this->rental_id])->sum('sum');
            $rental->balance = $sum;
            $rental->save();
        }
    }

}
