<?php

namespace app\models;

use Yii;
use app\helper\PseudoCrypt;
use yii\web\IdentityInterface;
use yii\base\NotSupportedException;

/**
 * This is the model class for table "rental".
 *
 * @property int $id
 * @property string $phone
 * @property string $mail
 * @property string $adress
 * @property int $radius
 * @property string $name
 * @property string $hash
 * @property string $coord
 * @property int $region_id
 *
 * @property RegionList $region
 * @property RentalGarage[] $rentalGarages
 */
class Rental extends \yii\db\ActiveRecord implements IdentityInterface
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'rental';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['adress'], 'string'],
            [['radius', 'region_id'], 'integer'],
            [['phone','coord', 'mail', 'name', 'hash'], 'string', 'max' => 255],
            [['region_id'], 'exist', 'skipOnError' => true, 'targetClass' => RegionList::className(), 'targetAttribute' => ['region_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'phone' => 'Phone',
            'mail' => 'Mail',
            'adress' => 'Adress',
            'radius' => 'Radius',
            'name' => 'Name',
            'hash' => 'Hash',
            'coord' => 'Coord',
            'region_id' => 'Region ID',
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id'=>$id]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByHash($hash)
    {
        return static::findOne(['hash' => $hash]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->hash;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($hash)
    {
        return $this->getAuthKey() === $hash;
    }

    public function findByUsername($name){
        return static::findOne(['name' => $name]);
    }



    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRegion()
    {
        return $this->hasOne(RegionList::className(), ['id' => 'region_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRentalGarages()
    {
        return $this->hasMany(RentalGarage::className(), ['rental_id' => 'id']);
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if($insert){
            $this->hash = PseudoCrypt::hash($this->id.time());
            $this->save();
        }else{
            $garage_list = $this->rentalGarages;
            if(!empty($garage_list)){
                foreach ($garage_list as $garage){
                    /* @var $garage \app\models\RentalGarage */
                    Yii::trace($garage);
                    $garage->radius = $this->radius;
                    $garage->region_id = $this->region_id;
                    if($garage->validate()){
                        $garage->save();
                    }
                }
            }
        }
    }
}
